// ICS (RFC 5545) timetable parsing — `lib/planner/ics.dart`.
//
// These tests exist because a timetable feed is the one input Openote will
// never get to fix at the source: it is generated by someone else's LMS, it is
// full of folding, escaping and recurrence, and the failure mode of getting it
// slightly wrong is a student sitting in the wrong room at the wrong time. Each
// test therefore pins a specific way that can happen, not the existence of a
// function.

import 'package:flutter_test/flutter_test.dart';

import 'package:openote/planner/ics.dart';

/// Assemble a calendar. The default CRLF is what RFC 5545 mandates; tests that
/// care about line endings pass their own.
String _cal(List<String> body, {String eol = '\r\n'}) =>
    ['BEGIN:VCALENDAR', 'VERSION:2.0', 'PRODID:-//Test//EN', ...body, 'END:VCALENDAR']
        .join(eol) +
    eol;

/// A whole calendar containing exactly one VEVENT built from [lines].
String _oneEvent(List<String> lines, {String eol = '\r\n'}) =>
    _cal(['BEGIN:VEVENT', ...lines, 'END:VEVENT'], eol: eol);

/// The window used by most tests: the first three weeks of August 2026,
/// in local time (2026-08-03 is a Monday).
final DateTime _augStart = DateTime(2026, 8, 1);
final DateTime _augEnd = DateTime(2026, 9, 1);

({List<IcsEvent> events, List<String> warnings}) _parse(String text,
        {DateTime? from, DateTime? to}) =>
    parseIcs(text, windowStart: from ?? _augStart, windowEnd: to ?? _augEnd);

bool _mentions(List<String> warnings, String needle) =>
    warnings.any((w) => w.toLowerCase().contains(needle.toLowerCase()));

void main() {
  group('unfolding (must happen before anything else)', () {
    test('a summary folded across three lines is rejoined, not truncated', () {
      // The bug: tokenising before unfolding leaves the value at the first
      // fold, so every lecture title longer than 75 octets loses its tail —
      // exactly the part that names the room and the week.
      final r = _parse(_oneEvent([
        'UID:folded@example.edu',
        'DTSTART:20260805T093000Z',
        'SUMMARY:COMP2521 Data Structures and Algorithms - Lecture (Week 3',
        ' , Ainsworth Building',
        ' , Theatre G03)',
      ]));
      expect(r.events, hasLength(1));
      expect(
        r.events.single.summary,
        'COMP2521 Data Structures and Algorithms - Lecture (Week 3'
        ', Ainsworth Building, Theatre G03)',
      );
    });

    test('a continuation beginning with two spaces keeps the second space', () {
      // RFC 5545 inserts exactly ONE space when folding. Eating both joins the
      // words either side and silently rewrites the producer's text.
      final r = _parse(_oneEvent([
        'UID:spaces@example.edu',
        'DTSTART:20260805T093000Z',
        'SUMMARY:Tutorial',
        '  group B',
      ]));
      expect(r.events.single.summary, 'Tutorial group B');
    });

    test('CRLF and LF feeds parse identically', () {
      // Most real generators on the Unix side emit bare LF despite the spec.
      // Handling only CRLF turns those feeds into one giant unparsed line.
      final lines = [
        'UID:eol@example.edu',
        'DTSTART:20260805T093000Z',
        'DTEND:20260805T110000Z',
        'SUMMARY:Physiology',
        ' 101',
      ];
      final crlf = _parse(_oneEvent(lines)).events;
      final lf = _parse(_oneEvent(lines, eol: '\n')).events;
      expect(crlf, hasLength(1));
      expect(lf, hasLength(1));
      expect(lf.single.summary, crlf.single.summary);
      expect(lf.single.summary, 'Physiology101');
      expect(lf.single.start.isAtSameMomentAs(crlf.single.start), isTrue);
    });

    test('a UTF-8 BOM does not swallow BEGIN:VCALENDAR', () {
      // A BOM survives decoding as U+FEFF, making the first property name
      // "\uFEFFBEGIN" — so the calendar looks like it has no events at all.
      final r = _parse('\uFEFF${_oneEvent([
            'UID:bom@example.edu',
            'DTSTART:20260805T093000Z',
            'SUMMARY:Statistics',
          ])}');
      expect(r.events, hasLength(1));
      expect(_mentions(r.warnings, 'BEGIN:VCALENDAR'), isFalse);
    });
  });

  group('DTSTART forms', () {
    test('a UTC DTSTART names an instant, not a wall clock', () {
      final r = _parse(_oneEvent([
        'UID:utc@example.edu',
        'DTSTART:20260805T093000Z',
        'DTEND:20260805T110000Z',
        'SUMMARY:Lecture',
      ]));
      final e = r.events.single;
      // Compared as an instant: converting to the device's zone must not move
      // the moment, only the digits shown.
      expect(e.start.isAtSameMomentAs(DateTime.utc(2026, 8, 5, 9, 30)), isTrue);
      expect(e.end!.isAtSameMomentAs(DateTime.utc(2026, 8, 5, 11)), isTrue);
      expect(e.start.isUtc, isFalse, reason: 'callers format local times');
      expect(e.allDay, isFalse);
      expect(e.tzid, isNull);
    });

    test('a TZID DTSTART is read as local wall clock and reports the zone', () {
      // The documented limitation: no timezone database, so the wall clock is
      // kept verbatim. It must SAY so, or a student travelling would never know
      // why the times look wrong.
      final r = _parse(_oneEvent([
        'UID:tz@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260805T093000',
        'DTEND;TZID=Australia/Sydney:20260805T110000',
        'SUMMARY:Lecture',
      ]));
      final e = r.events.single;
      expect(e.start, DateTime(2026, 8, 5, 9, 30));
      expect(e.end, DateTime(2026, 8, 5, 11));
      expect(e.tzid, 'Australia/Sydney');
      expect(_mentions(r.warnings, 'Australia/Sydney'), isTrue);
      expect(_mentions(r.warnings, 'local time'), isTrue);
    });

    test('VALUE=DATE gives an all-day event at local midnight', () {
      final r = _parse(_oneEvent([
        'UID:allday@example.edu',
        'DTSTART;VALUE=DATE:20260805',
        'DTEND;VALUE=DATE:20260806',
        'SUMMARY:Census date',
      ]));
      final e = r.events.single;
      expect(e.allDay, isTrue);
      expect(e.start, DateTime(2026, 8, 5));
      // The RFC's end is EXCLUSIVE and is deliberately left that way; a caller
      // that renders it inclusively must subtract a day itself.
      expect(e.end, DateTime(2026, 8, 6));
    });

    test('an impossible date is skipped, never rolled into the next month', () {
      // DateTime(2026, 2, 30) silently becomes 2 March. Accepting that would
      // put an exam on a day nobody published.
      final r = _parse(_cal([
        'BEGIN:VEVENT',
        'UID:bad@example.edu',
        'DTSTART:20260230T093000Z',
        'SUMMARY:Never happens',
        'END:VEVENT',
        'BEGIN:VEVENT',
        'UID:good@example.edu',
        'DTSTART:20260805T093000Z',
        'SUMMARY:Happens',
        'END:VEVENT',
      ]));
      expect(r.events, hasLength(1), reason: 'the good neighbour survives');
      expect(r.events.single.summary, 'Happens');
      expect(_mentions(r.warnings, 'not a valid date-time'), isTrue);
    });

    test('a VEVENT with no DTSTART is skipped with a warning', () {
      final r = _parse(_oneEvent([
        'UID:nostart@example.edu',
        'SUMMARY:Where does this go?',
      ]));
      expect(r.events, isEmpty);
      expect(_mentions(r.warnings, 'no DTSTART'), isTrue);
    });
  });

  group('TEXT escaping', () {
    test('escaped commas, semicolons, newlines and backslashes are decoded', () {
      final r = _parse(_oneEvent([
        'UID:esc@example.edu',
        'DTSTART:20260805T093000Z',
        r'SUMMARY:Lab 3\, Part 2\; bring a laptop\nRoom B\\C',
        r'LOCATION:Ainsworth\, Level 2',
        r'DESCRIPTION:Line one\nLine two',
      ]));
      final e = r.events.single;
      expect(e.summary, 'Lab 3, Part 2; bring a laptop\nRoom B\\C');
      expect(e.location, 'Ainsworth, Level 2');
      expect(e.description, 'Line one\nLine two');
    });

    test(r'a lone \N is a newline too', () {
      final r = _parse(_oneEvent([
        'UID:bign@example.edu',
        'DTSTART:20260805T093000Z',
        r'DESCRIPTION:First\NSecond',
      ]));
      expect(r.events.single.description, 'First\nSecond');
    });

    test('an escape RFC 5545 does not define is left verbatim', () {
      // Feeds carry unescaped Windows paths. Eating the backslash would quietly
      // corrupt text we were only asked to pass through.
      final r = _parse(_oneEvent([
        'UID:path@example.edu',
        'DTSTART:20260805T093000Z',
        r'DESCRIPTION:Slides at C:\temp\slides',
      ]));
      expect(r.events.single.description, r'Slides at C:\temp\slides');
    });
  });

  group('weekly recurrence', () {
    test('BYDAY expands to every listed weekday inside the window', () {
      // 2026-08-03 is a Monday.
      final r = _parse(
        _oneEvent([
          'UID:weekly@example.edu',
          'DTSTART;TZID=Australia/Sydney:20260803T090000',
          'DTEND;TZID=Australia/Sydney:20260803T100000',
          'SUMMARY:COMP1511 Lecture',
          'RRULE:FREQ=WEEKLY;BYDAY=MO,WE',
        ]),
        from: DateTime(2026, 8, 3),
        to: DateTime(2026, 8, 17),
      );
      expect(r.events.map((e) => e.start).toList(), <DateTime>[
        DateTime(2026, 8, 3, 9), // Mon
        DateTime(2026, 8, 5, 9), // Wed
        DateTime(2026, 8, 10, 9), // Mon
        DateTime(2026, 8, 12, 9), // Wed
      ]);
      expect(r.events.every((e) => e.recurrenceUnsupported), isFalse);
      expect(r.events.every((e) => e.uid == 'weekly@example.edu'), isTrue,
          reason: 'occurrences share the series UID — key on (uid, start)');
      expect(r.events.every((e) => e.end == e.start.add(const Duration(hours: 1))),
          isTrue);
    });

    test('COUNT limits the series from its start, not from the window', () {
      // The bug: counting occurrences inside the window instead of from
      // DTSTART turns COUNT=3 into three MORE lectures every time the agenda
      // window slides forward, so a finished course never ends.
      final ics = _oneEvent([
        'UID:count@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260803T090000',
        'SUMMARY:Intensive',
        'RRULE:FREQ=WEEKLY;COUNT=3',
      ]);
      final all = _parse(ics, from: DateTime(2026, 8, 1), to: DateTime(2026, 12, 1));
      expect(all.events.map((e) => e.start).toList(), <DateTime>[
        DateTime(2026, 8, 3, 9),
        DateTime(2026, 8, 10, 9),
        DateTime(2026, 8, 17, 9),
      ]);

      final late =
          _parse(ics, from: DateTime(2026, 8, 12), to: DateTime(2026, 12, 1));
      expect(late.events.map((e) => e.start).toList(),
          <DateTime>[DateTime(2026, 8, 17, 9)]);
    });

    test('UNTIL with a clock time is an inclusive bound', () {
      final r = _parse(
        _oneEvent([
          'UID:until@example.edu',
          'DTSTART:20260803T090000Z',
          'SUMMARY:Seminar',
          'RRULE:FREQ=WEEKLY;UNTIL=20260817T090000Z',
        ]),
        from: DateTime.utc(2026, 8, 1),
        to: DateTime.utc(2026, 12, 1),
      );
      expect(r.events, hasLength(3));
      expect(
        r.events.last.start.isAtSameMomentAs(DateTime.utc(2026, 8, 17, 9)),
        isTrue,
        reason: 'the occurrence landing exactly on UNTIL is included',
      );
    });

    test('a date-only UNTIL covers the whole of its own day', () {
      // The bug: treating UNTIL=20260817 as midnight drops that day's lecture,
      // so the last week of term quietly disappears from the timetable.
      final r = _parse(
        _oneEvent([
          'UID:untildate@example.edu',
          'DTSTART;TZID=Australia/Sydney:20260803T090000',
          'SUMMARY:Seminar',
          'RRULE:FREQ=WEEKLY;UNTIL=20260817',
        ]),
        from: DateTime(2026, 8, 1),
        to: DateTime(2026, 12, 1),
      );
      expect(r.events.map((e) => e.start).toList(), <DateTime>[
        DateTime(2026, 8, 3, 9),
        DateTime(2026, 8, 10, 9),
        DateTime(2026, 8, 17, 9),
      ]);
    });

    test('INTERVAL=2 aligns to the week, not to DTSTART plus fourteen days', () {
      // DTSTART is the Wednesday; BYDAY also names Monday, which falls EARLIER
      // in the same week. Expanding per-day from DTSTART puts that Monday in
      // week 1 or 3 — a fortnightly lab landing on the wrong Monday all term.
      final r = _parse(_oneEvent([
        'UID:fortnight@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260805T140000',
        'SUMMARY:Lab',
        'RRULE:FREQ=WEEKLY;INTERVAL=2;BYDAY=MO,WE',
      ]));
      expect(r.events.map((e) => e.start).toList(), <DateTime>[
        DateTime(2026, 8, 5, 14), // Wed, week 0 (Mon 3 Aug precedes DTSTART)
        DateTime(2026, 8, 17, 14), // Mon, week 2
        DateTime(2026, 8, 19, 14), // Wed, week 2
        DateTime(2026, 8, 31, 14), // Mon, week 4
      ]);
    });

    test('a floating weekly series keeps its wall-clock time across DST', () {
      // `DTSTART.add(Duration(days: 7))` adds absolute time, so the week the
      // clocks change the 09:00 lecture becomes 08:00 or 10:00 and stays wrong
      // for the rest of term. This only bites when the machine is in a zone
      // with DST; it is verified against TZ=America/New_York and
      // TZ=Australia/Sydney as well as UTC.
      final r = _parse(
        _oneEvent([
          'UID:dst@example.edu',
          'DTSTART;TZID=Australia/Sydney:20260803T090000',
          'DTEND;TZID=Australia/Sydney:20260803T100000',
          'SUMMARY:All-year lecture',
          'RRULE:FREQ=WEEKLY',
        ]),
        from: DateTime(2026, 8, 1),
        to: DateTime(2027, 8, 1),
      );
      expect(r.events.length, greaterThan(50));
      expect(r.events.every((e) => e.start.hour == 9 && e.start.minute == 0),
          isTrue,
          reason: 'every occurrence sits at 09:00 local, DST or not');
      expect(r.events.every((e) => e.start.weekday == DateTime.monday), isTrue);
    });

    test('a UTC weekly series keeps its UTC wall clock across DST', () {
      // The mirror of the previous case: a series pinned to UTC must NOT drift
      // with the device's local DST — 09:00Z stays 09:00Z, which is what a feed
      // publishing in UTC means by "same time every week".
      final r = _parse(
        _oneEvent([
          'UID:dstutc@example.edu',
          'DTSTART:20260803T090000Z',
          'SUMMARY:UTC weekly',
          'RRULE:FREQ=WEEKLY',
        ]),
        from: DateTime.utc(2026, 8, 1),
        to: DateTime.utc(2027, 8, 1),
      );
      expect(r.events.length, greaterThan(50));
      expect(
        r.events.every((e) {
          final utc = e.start.toUtc();
          return utc.hour == 9 && utc.minute == 0;
        }),
        isTrue,
      );
    });

    test('an unbounded weekly rule is bounded by the window, not by patience', () {
      // A rule with neither COUNT nor UNTIL is an infinite set. Walking it from
      // a 26-year-old DTSTART one week at a time is the "never hang" case.
      final r = _parse(
        _oneEvent([
          'UID:forever@example.edu',
          'DTSTART;TZID=Australia/Sydney:20000103T090000',
          'SUMMARY:Ancient weekly',
          'RRULE:FREQ=WEEKLY',
        ]),
        from: DateTime(2026, 8, 3),
        to: DateTime(2026, 8, 10),
      );
      expect(r.events.map((e) => e.start).toList(),
          <DateTime>[DateTime(2026, 8, 3, 9)]);
    });

    test('an occurrence already running at the window start is kept', () {
      // Skipping straight to the window would drop the lecture you are sitting
      // in, which is the one the agenda most needs to show.
      final r = _parse(
        _oneEvent([
          'UID:inprogress@example.edu',
          'DTSTART;TZID=Australia/Sydney:20000103T090000',
          'DTEND;TZID=Australia/Sydney:20000103T110000',
          'SUMMARY:Long-running weekly',
          'RRULE:FREQ=WEEKLY',
        ]),
        from: DateTime(2026, 8, 3, 10),
        to: DateTime(2026, 8, 4),
      );
      expect(r.events.map((e) => e.start).toList(),
          <DateTime>[DateTime(2026, 8, 3, 9)]);
    });

    test('an occurrence longer than its own interval is not skipped', () {
      // The narrow case the fast-forward's slack exists for. Jumping straight
      // to the window's own week is right only while an occurrence is shorter
      // than the gap between occurrences; a five-week block repeating weekly
      // means four earlier ones are still running, and landing on this week's
      // would silently lose them. Overlapping occurrences are odd but perfectly
      // legal, and an assessment-window feed is exactly this shape.
      //
      // Five expected starts rather than two on purpose: the fast-forward can
      // land a week early or late depending on how `inDays` truncates across a
      // DST boundary, and a two-row expectation is satisfiable by accident.
      final r = _parse(
        _oneEvent([
          'UID:overlapping@example.edu',
          'DTSTART;VALUE=DATE:20000103',
          'DTEND;VALUE=DATE:20000207', // thirty-five days, repeating every seven
          'SUMMARY:Assessment window',
          'RRULE:FREQ=WEEKLY',
        ]),
        from: DateTime(2026, 8, 3),
        to: DateTime(2026, 8, 3, 12),
      );
      expect(r.events.map((e) => e.start).toList(), <DateTime>[
        DateTime(2026, 7, 6),
        DateTime(2026, 7, 13),
        DateTime(2026, 7, 20),
        DateTime(2026, 7, 27),
        DateTime(2026, 8, 3), // begins exactly at the window start
      ]);
    });

    test('INTERVAL=0 is corrected instead of looping forever', () {
      final r = _parse(_oneEvent([
        'UID:zero@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260803T090000',
        'SUMMARY:Broken interval',
        'RRULE:FREQ=WEEKLY;INTERVAL=0;COUNT=3',
      ]));
      expect(r.events.map((e) => e.start).toList(), <DateTime>[
        DateTime(2026, 8, 3, 9),
        DateTime(2026, 8, 10, 9),
        DateTime(2026, 8, 17, 9),
      ]);
      expect(_mentions(r.warnings, 'INTERVAL'), isTrue);
    });

    test('a four-century window is capped rather than materialised', () {
      final r = _parse(
        _oneEvent([
          'UID:huge@example.edu',
          'DTSTART;TZID=Australia/Sydney:20000103T090000',
          'SUMMARY:Forever',
          'RRULE:FREQ=WEEKLY',
        ]),
        from: DateTime(2000),
        to: DateTime(2400),
      );
      expect(r.events, hasLength(2000), reason: 'the per-rule cap held');
      expect(_mentions(r.warnings, 'more than 2000 occurrences'), isTrue);
    });

    test('EXDATE hides the cancelled occurrence and only that one', () {
      final r = _parse(_oneEvent([
        'UID:exdate@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260803T090000',
        'SUMMARY:Weekly lecture',
        'RRULE:FREQ=WEEKLY',
        'EXDATE;TZID=Australia/Sydney:20260810T090000',
      ]));
      expect(r.events.map((e) => e.start).toList(), <DateTime>[
        DateTime(2026, 8, 3, 9),
        DateTime(2026, 8, 17, 9),
        DateTime(2026, 8, 24, 9),
        DateTime(2026, 8, 31, 9),
      ]);
    });

    test('a rescheduled instance replaces its slot instead of doubling it', () {
      // Without RECURRENCE-ID handling the student sees the lecture twice: once
      // where it used to be and once where it moved to.
      final r = _parse(_cal([
        'BEGIN:VEVENT',
        'UID:moved@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260803T090000',
        'SUMMARY:Weekly lecture',
        'RRULE:FREQ=WEEKLY;COUNT=3',
        'END:VEVENT',
        'BEGIN:VEVENT',
        'UID:moved@example.edu',
        'RECURRENCE-ID;TZID=Australia/Sydney:20260810T090000',
        'DTSTART;TZID=Australia/Sydney:20260811T140000',
        'SUMMARY:Weekly lecture (moved)',
        'END:VEVENT',
      ]));
      expect(r.events.map((e) => e.start).toList(), <DateTime>[
        DateTime(2026, 8, 3, 9),
        DateTime(2026, 8, 11, 14),
        DateTime(2026, 8, 17, 9),
      ]);
      expect(r.events[1].summary, 'Weekly lecture (moved)');
    });

    test('a DTSTART that does not match its own BYDAY is still shown', () {
      // RFC 5545 calls this undefined. Dropping the start date would lose an
      // event the producer explicitly wrote down.
      final r = _parse(
        _oneEvent([
          'UID:unsync@example.edu',
          'DTSTART;TZID=Australia/Sydney:20260804T090000', // Tuesday
          'SUMMARY:Odd series',
          'RRULE:FREQ=WEEKLY;BYDAY=MO;COUNT=3',
        ]),
        from: DateTime(2026, 8, 1),
        to: DateTime(2026, 9, 1),
      );
      expect(r.events.first.start, DateTime(2026, 8, 4, 9));
      expect(r.events.map((e) => e.start).toList(), <DateTime>[
        DateTime(2026, 8, 4, 9),
        DateTime(2026, 8, 10, 9),
        DateTime(2026, 8, 17, 9),
      ]);
      expect(_mentions(r.warnings, 'BYDAY does not include'), isTrue);
    });
  });

  group('recurrence this parser refuses to expand', () {
    test('a monthly RRULE is flagged, never expanded', () {
      final r = _parse(_oneEvent([
        'UID:monthly@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260805T160000',
        'SUMMARY:Department seminar',
        'RRULE:FREQ=MONTHLY;BYMONTHDAY=5',
      ]));
      expect(r.events, hasLength(1), reason: 'kept once, never twelve times');
      expect(r.events.single.start, DateTime(2026, 8, 5, 16));
      expect(r.events.single.recurrenceUnsupported, isTrue);
      expect(_mentions(r.warnings, 'FREQ=MONTHLY'), isTrue);
    });

    test('a daily RRULE is flagged rather than turned into weekly dates', () {
      final r = _parse(_oneEvent([
        'UID:daily@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260805T160000',
        'SUMMARY:Daily standup',
        'RRULE:FREQ=DAILY;COUNT=5',
      ]));
      expect(r.events, hasLength(1));
      expect(r.events.single.recurrenceUnsupported, isTrue);
    });

    test('BYDAY with an ordinal is refused, not read as "every Monday"', () {
      // "2MO" means the second Monday of a period. Expanding it as plain MO
      // puts four occurrences where one belongs — inventing dates, which is the
      // one thing worse than showing too few.
      final r = _parse(_oneEvent([
        'UID:ordinal@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260803T090000',
        'SUMMARY:Second-Monday meeting',
        'RRULE:FREQ=WEEKLY;BYDAY=2MO',
      ]));
      expect(r.events, hasLength(1));
      expect(r.events.single.recurrenceUnsupported, isTrue);
      expect(_mentions(r.warnings, 'BYDAY'), isTrue);
    });

    test('an unhandled BY-part downgrades the rule instead of ignoring it', () {
      // BYMONTH=9,10 narrows the set. Silently dropping the part would expand
      // the rule across every month of the year.
      final r = _parse(_oneEvent([
        'UID:bymonth@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260803T090000',
        'SUMMARY:Term-only lecture',
        'RRULE:FREQ=WEEKLY;BYDAY=MO;BYMONTH=9,10',
      ]));
      expect(r.events, hasLength(1));
      expect(r.events.single.recurrenceUnsupported, isTrue);
      expect(_mentions(r.warnings, 'BYMONTH'), isTrue);
    });

    test('an RRULE with no FREQ is flagged, not assumed weekly', () {
      final r = _parse(_oneEvent([
        'UID:nofreq@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260803T090000',
        'SUMMARY:Malformed rule',
        'RRULE:COUNT=4',
      ]));
      expect(r.events, hasLength(1));
      expect(r.events.single.recurrenceUnsupported, isTrue);
      expect(_mentions(r.warnings, 'RRULE has no FREQ'), isTrue);
    });
  });

  group('end times', () {
    test('DURATION is used when DTEND is absent', () {
      // Outlook-published feeds routinely omit DTEND. Without DURATION support
      // every one of those lectures renders with no finishing time.
      final r = _parse(_oneEvent([
        'UID:dur@example.edu',
        'DTSTART:20260805T093000Z',
        'DURATION:PT1H30M',
        'SUMMARY:Workshop',
      ]));
      final e = r.events.single;
      expect(e.end!.isAtSameMomentAs(DateTime.utc(2026, 8, 5, 11)), isTrue);
    });

    test('DTEND before DTSTART drops the end rather than inverting the event', () {
      final r = _parse(_oneEvent([
        'UID:backwards@example.edu',
        'DTSTART:20260805T093000Z',
        'DTEND:20260805T083000Z',
        'SUMMARY:Time traveller',
      ]));
      expect(r.events.single.end, isNull);
      expect(_mentions(r.warnings, 'DTEND is before DTSTART'), isTrue);
    });
  });

  group('component nesting', () {
    test("a VALARM's own properties are never offered to the event", () {
      // A parser that scans for property names anywhere gives every event its
      // alarm's text instead of the lecturer's notes. The alarm is placed
      // BEFORE the event's own DESCRIPTION on purpose: with it second, the
      // "first value wins" rule would mask the bug and this test would pass
      // against a parser that has no idea VALARM exists.
      final r = _parse(_oneEvent([
        'UID:alarm@example.edu',
        'DTSTART:20260805T093000Z',
        'BEGIN:VALARM',
        'ACTION:DISPLAY',
        'DESCRIPTION:Reminder: Lecture in 15 minutes',
        'SUMMARY:Alarm subject line',
        'TRIGGER:-PT15M',
        'END:VALARM',
        'SUMMARY:Lecture',
        'DESCRIPTION:Bring the course reader',
      ]));
      final e = r.events.single;
      expect(e.description, 'Bring the course reader');
      expect(e.summary, 'Lecture');
      expect(_mentions(r.warnings, 'Duplicate'), isFalse,
          reason: 'the alarm lines were skipped outright, not merely outranked');
    });

    test("a VTIMEZONE's own DTSTART and RRULE are not read as an event", () {
      // VTIMEZONE > STANDARD carries DTSTART and a yearly RRULE. Treating those
      // as event properties invents a recurring "event" out of a DST rule. The
      // second VEVENT is the other half of the check: if the nested
      // BEGIN/END:STANDARD left the component stack unbalanced, the events
      // either side of the timezone block would stop parsing.
      final r = _parse(_cal([
        'BEGIN:VEVENT',
        'UID:before@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260804T093000',
        'SUMMARY:Before the timezone block',
        'END:VEVENT',
        'BEGIN:VTIMEZONE',
        'TZID:Australia/Sydney',
        'BEGIN:STANDARD',
        'DTSTART:19700405T030000',
        'RRULE:FREQ=YEARLY;BYMONTH=4;BYDAY=1SU',
        'TZOFFSETFROM:+1100',
        'TZOFFSETTO:+1000',
        'END:STANDARD',
        'END:VTIMEZONE',
        'BEGIN:VEVENT',
        'UID:after@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260805T093000',
        'SUMMARY:After the timezone block',
        'END:VEVENT',
      ]));
      expect(r.events.map((e) => e.summary).toList(),
          <String>['Before the timezone block', 'After the timezone block']);
      expect(r.events.every((e) => e.recurrenceUnsupported), isFalse);
      expect(_mentions(r.warnings, 'YEARLY'), isFalse,
          reason: 'the timezone rule was never even looked at');
      expect(_mentions(r.warnings, 'malformed'), isFalse);
    });
  });

  group('malformed input', () {
    test('a file truncated mid-VEVENT keeps what it had already read', () {
      // A cut-off download is the common case. Losing today's whole agenda
      // because the last event is incomplete is the wrong trade.
      const text = 'BEGIN:VCALENDAR\r\n'
          'VERSION:2.0\r\n'
          'BEGIN:VEVENT\r\n'
          'UID:complete@example.edu\r\n'
          'DTSTART:20260805T093000Z\r\n'
          'SUMMARY:Complete\r\n'
          'END:VEVENT\r\n'
          'BEGIN:VEVENT\r\n'
          'UID:cut@example.edu\r\n'
          'DTSTART:20260806T093000Z\r\n'
          'SUMMARY:Cut off half way thro';
      final r = _parse(text);
      expect(r.events.map((e) => e.uid).toList(),
          <String>['complete@example.edu', 'cut@example.edu']);
      expect(_mentions(r.warnings, 'ended in the middle of a VEVENT'), isTrue);
    });

    test('a file with no VEVENTs returns nothing and says why', () {
      final r = _parse(_cal([
        'BEGIN:VTIMEZONE',
        'TZID:Australia/Sydney',
        'END:VTIMEZONE',
      ]));
      expect(r.events, isEmpty);
      expect(_mentions(r.warnings, 'No VEVENT'), isTrue);
    });

    test('an empty feed never throws', () {
      final r = _parse('');
      expect(r.events, isEmpty);
      expect(r.warnings, isNotEmpty);
    });

    test('arbitrary non-calendar text never throws or hangs', () {
      final r = _parse('this is not a calendar\r\n'
          ':::::\r\n'
          'BEGIN\r\n'
          'END:VEVENT\r\n'
          ';;;;;\r\n'
          'DTSTART;TZID=:\r\n'
          'RRULE:FREQ=WEEKLY;;;=\r\n');
      expect(r.events, isEmpty);
      expect(r.warnings, isNotEmpty);
    });

    test('a duplicate SUMMARY keeps the first value deterministically', () {
      // RFC 5545 forbids the repetition, so there is no defensible way to pick
      // between them; "first wins" at least survives the producer reordering
      // its output between two refreshes.
      final r = _parse(_oneEvent([
        'UID:dup@example.edu',
        'DTSTART:20260805T093000Z',
        'SUMMARY:First',
        'SUMMARY:Second',
      ]));
      expect(r.events.single.summary, 'First');
      expect(_mentions(r.warnings, 'Duplicate SUMMARY'), isTrue);
    });

    test('a quoted parameter containing a colon does not split the line early', () {
      // Splitting on the first colon turns TZID="A:B" into a value of `B"...`
      // and loses the DTSTART entirely.
      final r = _parse(_oneEvent([
        'UID:quoted@example.edu',
        'DTSTART;TZID="Custom:Zone";VALUE=DATE-TIME:20260805T093000',
        'SUMMARY:Quoted param',
      ]));
      final e = r.events.single;
      expect(e.tzid, 'Custom:Zone');
      expect(e.start, DateTime(2026, 8, 5, 9, 30));
    });

    test('a missing UID is reported, never invented', () {
      final r = _parse(_oneEvent([
        'DTSTART:20260805T093000Z',
        'SUMMARY:Anonymous',
      ]));
      expect(r.events.single.uid, '');
      expect(_mentions(r.warnings, 'no UID'), isTrue);
    });

    test('lower-case property names are honoured', () {
      // RFC 5545 names are case-insensitive and some generators lower-case them.
      final r = _parse('begin:VCALENDAR\r\n'
          'begin:vevent\r\n'
          'uid:lower@example.edu\r\n'
          'dtstart:20260805T093000Z\r\n'
          'summary:Lower case\r\n'
          'end:vevent\r\n'
          'end:VCALENDAR\r\n');
      expect(r.events.single.summary, 'Lower case');
    });
  });

  // Every test below was written against a parser that already passed the ones
  // above: each names a way the first version got a real feed wrong.
  group('defects found by adversarial review', () {
    test("an all-day event survives a window that starts after midnight", () {
      // RFC 5545 §3.6.1: DTSTART as a DATE with neither DTEND nor DURATION
      // lasts one day. Read as a zero-length point instead, it is "before the
      // window start" from 00:00:01 onwards — so an agenda built as "the next
      // seven days from now" lost today's census date, silently, with no
      // warning to explain the gap.
      final r = _parse(
        _oneEvent([
          'UID:allday-nodtend@example.edu',
          'DTSTART;VALUE=DATE:20260805',
          'SUMMARY:Census date',
        ]),
        from: DateTime(2026, 8, 5, 9),
        to: DateTime(2026, 8, 12),
      );
      expect(r.events, hasLength(1));
      expect(r.events.single.start, DateTime(2026, 8, 5));
      // The implied day is used for windowing only: `end` still distinguishes
      // an end the feed stated from one the RFC merely implies.
      expect(r.events.single.end, isNull);
    });

    test('an all-day occurrence of a series survives the same window', () {
      final r = _parse(
        _oneEvent([
          'UID:allday-series@example.edu',
          'DTSTART;VALUE=DATE:20260803',
          'SUMMARY:Weekly reading day',
          'RRULE:FREQ=WEEKLY',
        ]),
        from: DateTime(2026, 8, 10, 9),
        to: DateTime(2026, 8, 11),
      );
      expect(r.events.map((e) => e.start).toList(),
          <DateTime>[DateTime(2026, 8, 10)]);
    });

    test('one unreadable VEVENT does not take the rest of the feed with it', () {
      // `7 * interval * k` overflowed int64 for this INTERVAL, producing a
      // negative day count that made `DateTime` throw. With the only try/catch
      // wrapped around the whole parse, that returned ZERO events — discarding
      // the perfectly good VEVENT beside it, which is precisely the trade the
      // library note promises never to make.
      final r = _parse(
        _cal([
          'BEGIN:VEVENT',
          'UID:hostile@example.edu',
          'DTSTART:20260803T090000Z',
          'SUMMARY:Absurd interval',
          'RRULE:FREQ=WEEKLY;INTERVAL=999999999999999999',
          'END:VEVENT',
          'BEGIN:VEVENT',
          'UID:bystander@example.edu',
          'DTSTART:20260805T090000Z',
          'SUMMARY:Innocent bystander',
          'END:VEVENT',
        ]),
        from: DateTime.utc(2026, 8, 1),
        to: DateTime.utc(2026, 9, 1),
      );
      expect(r.events.map((e) => e.summary).toList(),
          <String>['Absurd interval', 'Innocent bystander'],
          reason: 'both survive, and an interval that huge yields one occurrence');
    });

    test('a valid feed with repeated ATTENDEE lines raises no complaint', () {
      // RFC 5545 lets ATTENDEE, CATEGORIES, COMMENT and RELATED-TO repeat, and
      // any invitation-style feed has one ATTENDEE per person. Warning on every
      // repeated name filled the "feed problems" list with four assertions that
      // are simply untrue, which teaches the reader to ignore the ones that
      // matter.
      final r = _parse(_oneEvent([
        'UID:attendees@example.edu',
        'DTSTART:20260805T090000Z',
        'SUMMARY:Group project meeting',
        'ATTENDEE;CN=Alice:mailto:alice@example.edu',
        'ATTENDEE;CN=Bob:mailto:bob@example.edu',
        'CATEGORIES:LECTURE',
        'CATEGORIES:COMP1511',
        'COMMENT:One',
        'COMMENT:Two',
      ]));
      expect(r.events, hasLength(1));
      expect(_mentions(r.warnings, 'Duplicate'), isFalse);
      // A repeat of a genuinely single-valued property is still reported.
      final dup = _parse(_oneEvent([
        'UID:dup2@example.edu',
        'DTSTART:20260805T090000Z',
        'SUMMARY:First',
        'SUMMARY:Second',
      ]));
      expect(_mentions(dup.warnings, 'Duplicate SUMMARY'), isTrue);
    });

    test('a multi-day block keeps a midnight end across a DST change', () {
      // The span is measured once, at DTSTART, and was then added as absolute
      // time to every later occurrence. On the week the clocks change that put
      // an all-day block's exclusive end at 23:00 the day before it should be
      // — and a UI subtracting a day to render it inclusively then shows a
      // two-day block as one. Meaningful only where the machine has DST; run
      // under TZ=America/New_York, where it fails without the fix on the weeks
      // of 2026-03-08 and 2026-11-01.
      final r = _parse(
        _oneEvent([
          'UID:block@example.edu',
          'DTSTART;VALUE=DATE:20261010',
          'DTEND;VALUE=DATE:20261012',
          'SUMMARY:Two-day block',
          'RRULE:FREQ=WEEKLY',
        ]),
        from: DateTime(2026, 10, 1),
        to: DateTime(2026, 12, 1),
      );
      expect(r.events, isNotEmpty);
      for (final e in r.events) {
        expect(e.end, DateTime(e.start.year, e.start.month, e.start.day + 2),
            reason: 'every occurrence ends at midnight two days on, DST or not');
      }
    });

    test('an UNTIL before its own DTSTART shows the event, not nothing', () {
      // The rule's set is empty, so the event vanished with no row and no
      // warning — the reader had no way to know a lecture had been dropped.
      // RFC 5545 calls DTSTART the first instance of the recurrence set.
      final r = _parse(
        _oneEvent([
          'UID:backwards-until@example.edu',
          'DTSTART:20260805T090000Z',
          'SUMMARY:Contradictory rule',
          'RRULE:FREQ=WEEKLY;UNTIL=20260701T000000Z',
        ]),
        from: DateTime.utc(2026, 8, 1),
        to: DateTime.utc(2026, 9, 1),
      );
      expect(r.events, hasLength(1));
      expect(r.events.single.start.isAtSameMomentAs(DateTime.utc(2026, 8, 5, 9)),
          isTrue);
      expect(_mentions(r.warnings, 'UNTIL is before'), isTrue);
    });

    test('RDATE is reported rather than dropped in silence', () {
      // RDATE adds real, explicitly-written dates to a series. Not expanding
      // them is a scope decision; not SAYING so means a catch-up tutorial the
      // producer published never appears and nothing anywhere hints at it.
      final r = _parse(_oneEvent([
        'UID:rdate@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260803T090000',
        'SUMMARY:Series with an extra session',
        'RRULE:FREQ=WEEKLY;COUNT=2',
        'RDATE;TZID=Australia/Sydney:20260807T140000',
      ]));
      expect(r.events, hasLength(2), reason: 'the RRULE part still expands');
      expect(_mentions(r.warnings, 'RDATE'), isTrue);
    });
  });

  group('window', () {
    test('the window is half-open: start inclusive, end exclusive', () {
      // Consecutive windows must neither duplicate nor drop a row, or a daily
      // refresh shows yesterday's 09:00 lecture twice.
      final text = _cal([
        'BEGIN:VEVENT',
        'UID:at-start@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260805T100000',
        'SUMMARY:Exactly at start',
        'END:VEVENT',
        'BEGIN:VEVENT',
        'UID:at-end@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260805T120000',
        'SUMMARY:Exactly at end',
        'END:VEVENT',
        'BEGIN:VEVENT',
        'UID:ended@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260805T090000',
        'DTEND;TZID=Australia/Sydney:20260805T100000',
        'SUMMARY:Ends exactly at start',
        'END:VEVENT',
        'BEGIN:VEVENT',
        'UID:straddles@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260805T090000',
        'DTEND;TZID=Australia/Sydney:20260805T110000',
        'SUMMARY:Straddles the start',
        'END:VEVENT',
      ]);
      final r = _parse(text,
          from: DateTime(2026, 8, 5, 10), to: DateTime(2026, 8, 5, 12));
      expect(r.events.map((e) => e.uid).toSet(),
          <String>{'at-start@example.edu', 'straddles@example.edu'});
    });

    test('an inverted window returns nothing and says why', () {
      // Otherwise the user sees an empty agenda with no explanation for it.
      final r = _parse(
        _oneEvent([
          'UID:x@example.edu',
          'DTSTART:20260805T093000Z',
          'SUMMARY:Lecture',
        ]),
        from: DateTime(2026, 9, 1),
        to: DateTime(2026, 8, 1),
      );
      expect(r.events, isEmpty);
      expect(_mentions(r.warnings, 'window ends at or before it starts'), isTrue);
    });

    test('events come back in chronological order regardless of file order', () {
      final r = _parse(_cal([
        'BEGIN:VEVENT',
        'UID:c@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260807T090000',
        'SUMMARY:Third',
        'END:VEVENT',
        'BEGIN:VEVENT',
        'UID:a@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260803T090000',
        'SUMMARY:First',
        'END:VEVENT',
        'BEGIN:VEVENT',
        'UID:b@example.edu',
        'DTSTART;TZID=Australia/Sydney:20260805T090000',
        'SUMMARY:Second',
        'END:VEVENT',
      ]));
      expect(r.events.map((e) => e.summary).toList(),
          <String>['First', 'Second', 'Third']);
    });
  });
}
